// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXWzcyuul8kDtk_kSdTsfQQMLK6Va2O4E',
    appId: '1:991716246619:web:c7dbaca5d89ad128d62b7e',
    messagingSenderId: '991716246619',
    projectId: 'oyuncaktakasi-ee3fb',
    authDomain: 'oyuncaktakasi-ee3fb.firebaseapp.com',
    storageBucket: 'oyuncaktakasi-ee3fb.appspot.com',
    measurementId: 'G-HC2P38EEEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BlRLm-N0Dsyo7SHHYwAO0HK4uj77XDs',
    appId: '1:991716246619:android:c5feb326c7178f66d62b7e',
    messagingSenderId: '991716246619',
    projectId: 'oyuncaktakasi-ee3fb',
    storageBucket: 'oyuncaktakasi-ee3fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7xezzCCFXAjmAkkc02gRQOvFg5MW4_q0',
    appId: '1:991716246619:ios:17ea877a0bd3c623d62b7e',
    messagingSenderId: '991716246619',
    projectId: 'oyuncaktakasi-ee3fb',
    storageBucket: 'oyuncaktakasi-ee3fb.appspot.com',
    iosClientId:
        '991716246619-rv62p8f7774a6glk1bufa1cc79vclhrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.oyuncakTakasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7xezzCCFXAjmAkkc02gRQOvFg5MW4_q0',
    appId: '1:991716246619:ios:17ea877a0bd3c623d62b7e',
    messagingSenderId: '991716246619',
    projectId: 'oyuncaktakasi-ee3fb',
    storageBucket: 'oyuncaktakasi-ee3fb.appspot.com',
    iosClientId:
        '991716246619-rv62p8f7774a6glk1bufa1cc79vclhrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.oyuncakTakasi',
  );
}
